spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
server:
  port: 6699
spring:
  application:
    name: AIGOU_PLAT

---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
server:
  port: 9966
spring:
  application:
    name: AIGOU_PLAT

